config/routes.rb
Rails.application.routes.draw do
  resources :chat_logs do
    get :delete
  end

  namespace :static do
    get :home
    get :admin
  end

  root 'static#home'

  devise_for :users
end

app/models/chat_log.rb
class ChatLog < ActiveRecord::Base
  include Authority::Abilities

  self.authorizer = AllUsersAuthorizer

  belongs_to :user

  default_scope -> { order(created_at: :desc) }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             polymorphic: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  include Authority::Abilities
  include Authority::UserAbilities

  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  self.authorizer = AdminAuthorizer

  def display_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_logs_controller.rb
class ChatLogsController < ApplicationController
  respond_to :js

  before_action :authenticate_user!
  before_action :set_chat_log, only: [:show, :edit, :update, :destroy]

  authorize_actions_for ChatLog

  authority_actions delete: 'delete'

  # GET /chat_logs
  def index
    set_chat_logs
  end

  # GET /chat_logs/1
  def show
  end

  # GET /chat_logs/new
  def new
    @chat_log = ChatLog.new
  end

  # GET /chat_logs/1/edit
  def edit
  end

  # POST /chat_logs
  def create
    authorize_action_for(ChatLog)
    @chat_log = ChatLog.new(chat_log_params)
    @chat_log.user_id = current_user.id
    @chat_log.save
    set_chat_logs
   end

  # PATCH/PUT /chat_logs/1
  def update
    authorize_action_for(@chat_log)
    @chat_log.update(chat_log_params)
    set_chat_logs
  end

  def delete
    @chat_log = ChatLog.find(params[:chat_log_id])
  end

  # DELETE /chat_logs/1
  def destroy
    authorize_action_for(@chat_log)
    @chat_log.destroy
    set_chat_logs
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_log
      @chat_log = ChatLog.find(params[:id])
    end

    def set_chat_logs
      @chat_logs = ChatLog.all
    end

    # Only allow a trusted parameter "white list" through.
    def chat_log_params
      params.require(:chat_log).permit(:user_id, :message)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :authenticate_user!

  def home
  end

  def admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_logs_helper.rb
module ChatLogsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/chat_logs/_delete.html.erb
<div class="modal-header">
  <h3>Delete Chat Log</h3>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @chat_log %></b>?
</div>
<div class="modal-footer">
  <%= link_to 'Yes, Delete This Chat Log', chat_log_path(@chat_log), method: :delete, remote: true, class: 'btn btn-danger' %>
  <%= link_to 'No, Please Don\'t', '#', class: 'btn', data: { dismiss: 'modal' } %>
</div>

app/views/chat_logs/_form.html.erb
<%= simple_form_for @chat_log, remote:true do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="form-inputs">
      <%= f.input :message %>
    </div>
  </div>

  <div class="modal-footer">
    <%= f.submit class: 'btn btn-success', data: { disable_with: 'Submitting...' } %>
    <%= link_to 'Cancel', '#', class: 'btn', data: { dismiss: 'modal' } %>
  </div>
<% end %>

app/views/chat_logs/_index.html.erb
<table id="chat_logs" class="table table-striped">
  <thead>
  <tr>
    <th>User</th>
    <th>Message</th>
    <th>Date</th>
    <th colspan="3" width="30%">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @chat_logs.each do |chat_log| %>
  <tr>
    <td><%= chat_log.user.display_name %></td>
    <td><%= chat_log.message %></td>
    <td><%= chat_log.created_at.in_time_zone('EST').strftime('%b %d, %Y at %l:%M %p') %></td>
    <td><%= link_to 'Show', chat_log, class: 'btn btn-default   btn-small', remote:true if current_user.can_read?(chat_log) %></td>
    <td><%= link_to 'Edit', edit_chat_log_path(chat_log), class: 'btn btn-warning btn-small', remote:true if current_user.can_update?(chat_log) %></td>
    <td><%= link_to 'Delete', chat_log_delete_path(chat_log), class: 'btn btn-danger btn-small', remote:true if current_user.can_delete?(chat_log) %></td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/chat_logs/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 class="modal-title">Add Chat Log</h3>
</div>
<%= render 'form' %>

app/views/chat_logs/_save.js.erb
$("ul.errors").html("");
<% if @chat_log.errors.any? %>
  <% @chat_log.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $("#chat_logs").html("<%= escape_javascript(render 'index') %>");
  $("#chat_log-modal").modal("hide");
<% end %>

app/views/chat_logs/create.js.erb
<%= render 'save' %>

app/views/chat_logs/delete.js.erb
$("#chat_log-modal .modal-content").html("<%= escape_javascript(render 'delete') %>");
$("#chat_log-modal").modal("show");

app/views/chat_logs/destroy.js.erb
<%= render 'save' %>

app/views/chat_logs/edit.js.erb
$("#chat_log-modal .modal-content").html("<%= escape_javascript(render 'edit') %>");
$("#chat_log-modal").modal("show");

app/views/chat_logs/index.html.erb
<h1>Chat Log</h1>
<%= link_to 'New Chat log', new_chat_log_path, class: 'btn btn-primary btn-small', remote: true if current_user.can_create?(ChatLog) %>
<%= render 'index' %>

<div class="modal fade" id="chat_log-modal" tabindex="-1" role="dialog" aria-labelledby="chat_logLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/chat_logs/new.js.erb
$("#chat_log-modal .modal-content").html("<%= escape_javascript(render 'new') %>");
$("#chat_log-modal").modal("show");

app/views/chat_logs/show.html.erb
  <p>
    <strong>User:</strong>
    <%= @chat_log.user %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= @chat_log.message %>
  </p>

<%= link_to 'Edit', edit_chat_log_path(@chat_log), class: 'btn btn-warning btn-small' %>
<%= link_to 'Back', chat_logs_path, class: 'btn btn-small' %>

app/views/chat_logs/show.js.erb
$("#chat_log-modal .modal-content").html("<%= escape_javascript(render 'details') %>");
$("#chat_log-modal").modal("show");

app/views/chat_logs/update.js.erb
<%= render 'save' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="<%= root_path %>" class="navbar-brand">
        <span style="display:inline-block;">Sample App</span>
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <% if user_signed_in? %>
        <div class="more-button dropdown pull-right">
          <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <i class="fa fa-2x fa-bars"></i>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <% if current_user.has_role?(:admin) %>
                <li><%= link_to 'Admin', static_admin_path %></li>
            <% end %>

            <li><%= link_to 'Sign out', destroy_user_session_path, data:{method: :delete} %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>

<% else %>
  <li><%= link_to 'Home', static_home_path %></li>
  <li><%= link_to 'Chat Log', chat_logs_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || 'Example App' %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if content_for?(:document_head_content) %>
      <%= yield(:document_head_content) %>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap">
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <div class="container">

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 text-center">
        <%= render 'layouts/messages' %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>